services:
  webb-app:
    container_name: webb
    image: webbinspace
    build: .
    ports:
      - 8000:8000 # expose ports - HOST:CONTAINER
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
      #- DB_ENGINE=django.db.backends.postgresql
      #- DB_NAME=
      #- DB_USER=
      #- DB_PASSWORD=
      #- DB_HOST=webb-db
      #- DB_PORT=5432

  #webb-db:
  #  image: postgres:15.1
  #  environment:
  #    - POSTGRES_DB=
  #    - POSTGRES_USER=
  #    - POSTGRES_PASSWORD=