version: "3.9"

services:
  web:
    container_name: webb
    image: webbinspace
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" # expose ports - HOST:CONTAINER
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}