# Generated by Django 4.1 on 2022-08-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(max_length=10)),
                ('date_code', models.SmallIntegerField()),
                ('cycle', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(default='', max_length=10)),
                ('pcs_mode', models.CharField(default='', max_length=10)),
                ('visit_type', models.CharField(default='', max_length=30)),
                ('scheduled_start_time', models.DateTimeField(null=True)),
                ('duration', models.DateTimeField(null=True)),
                ('science_instrument_and_mode', models.CharField(default='', max_length=50)),
                ('instrument', models.CharField(choices=[('1', 'NIRCam'), ('2', 'NIRSpec'), ('3', 'MIRI'), ('4', 'NIRISS')], default='', max_length=1)),
                ('mode', models.CharField(default='', max_length=50)),
                ('target_name', models.CharField(default='', max_length=30)),
                ('keywords', models.CharField(default='', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='webb.category')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='webb.report')),
            ],
        ),
    ]
