# Generated by Django 4.1 on 2022-09-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='package_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
