# Generated by Django 4.1 on 2022-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0003_remove_visit_mode_alter_visit_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='instrument',
            field=models.CharField(choices=[('1', 'NIRCam'), ('2', 'NIRSpec'), ('3', 'MIRI'), ('4', 'NIRISS')], max_length=1, null=True),
        ),
    ]
