# Generated by Django 4.1 on 2022-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0004_alter_visit_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
