# Generated by Django 4.1 on 2022-10-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0006_visit_invalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='invalid',
        ),
    ]
