# Generated by Django 4.1.5 on 2023-01-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0008_visit_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
