# Generated by Django 4.2.4 on 2023-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0009_report_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='package_number',
            field=models.CharField(max_length=10),
        ),
    ]
