# Generated by Django 4.2.4 on 2023-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0010_report_report_code_alter_report_package_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
